config/routes.rb
Rails.application.routes.draw do

  resources :experiences
  

  root 'home#index'
  get 'contact', to: 'home#contact'

end

app/models/experience.rb
class EndTimeValidator < ActiveModel::Validator
  def validate(record)
    if record.start_date and record.end_date
      if record.start_date > record.end_date
        record.errors[:base] << "End date couldn't be earlier than start date"
      end
      if DateTime.current < record.end_date
        record.errors[:base] << "End date couldn't be in the future"
      end
    end
  end
end

class Experience < ActiveRecord::Base
  validates :company, :description, :start_date, presence: true
  validates_with EndTimeValidator
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: [:show, :edit, :update, :destroy]

  # GET /experiences
  # GET /experiences.json
  def index
    @experiences = Experience.all
  end

  # GET /experiences/1
  # GET /experiences/1.json
  def show
  end

  # GET /experiences/new
  def new
    @experience = Experience.new
  end

  # GET /experiences/1/edit
  def edit
  end

  # POST /experiences
  # POST /experiences.json
  def create
    @experience = Experience.new(experience_params)

    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: 'Experience was successfully created.' }
        format.json { render :show, status: :created, location: @experience }
      else
        format.html { render :new }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiences/1
  # PATCH/PUT /experiences/1.json
  def update
    respond_to do |format|
      if @experience.update(experience_params)
        format.html { redirect_to @experience, notice: 'Experience was successfully updated.' }
        format.json { render :show, status: :ok, location: @experience }
      else
        format.html { render :edit }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiences/1
  # DELETE /experiences/1.json
  def destroy
    @experience.destroy
    respond_to do |format|
      format.html { redirect_to experiences_url, notice: 'Experience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_experience
      @experience = Experience.find(params[:id])
    end

    def experience_params
      params[:experience].permit(:company, :description, :start_date, :end_date)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/experiences/_form.html.haml
= form_for @experience do |f|
  - if @experience.errors.any?
    #error_explanation
      %h2= "#{pluralize(@experience.errors.count, "error")} prohibited this experience from being saved:"
      %ul
        - @experience.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/experiences/edit.html.haml
%h1 Editing experience

= render 'form'

= link_to 'Show', @experience
\|
= link_to 'Back', experiences_path

app/views/experiences/index.html.haml
%h1 Listing experiences

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @experiences.each do |experience|
      %tr
        %td= link_to 'Show', experience
        %td= link_to 'Edit', edit_experience_path(experience)
        %td= link_to 'Destroy', experience, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Experience', new_experience_path

app/views/experiences/new.html.haml
%h1 New experience

= render 'form'

= link_to 'Back', experiences_path

app/views/experiences/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_experience_path(@experience)
\|
= link_to 'Back', experiences_path

app/views/home/contact.html.haml
%h1 Home#contact
%p Find me in app/views/home/contact.html.erb

app/views/home/index.html.haml
.row.first-slide
  .large-4.large-offset-2.small-10.small-offset-1.columns.content.padding.border-radius
    %h2 Hej
    %p Chcesz rzucić okiem na moją osobę?
    %p Zerknąć na realizowane projekty?
    %p A może poprostu zobaczyć kim jestem?
.row.second-slide
  .large-12.columns.center
    %p Hejos
  .large-12.columns.center
    %p Hejos
  .large-12.columns.center
    %p Hejos
  .large-12.columns.center
    %p Hejos
  %hr
.row.third-slide
  .large-12.columns.center
    %p Hejos
  .large-12.columns.center
    %p Hejos
  .large-12.columns.center
    %p Hejos
  .large-12.columns.center
    %p Hejos
.row.third-slide
  .large-12.columns.center
    %p Hejos
  .large-12.columns.center
    %p Hejos
  .large-12.columns.center
    %p Hejos
  .large-12.columns.center
    %p Hejos
.row.third-slide
  .large-12.columns.center
    %p Hejos
  .large-12.columns.center
    %p Hejos
  .large-12.columns.center
    %p Hejos
  .large-12.columns.center
    %p Hejos

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
.row.navigation
  %nav.margin-bottom
    .large-6.columns
      = link_to root_path do
        %h1.name
          %span Michał Korulczyk
        
    .large-6.columns
      = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
.icon-bar.four-up
  =link_to experiences_path, class: 'item' do
    = image_tag('icons/tools.svg')
    %label Praca
  %a.item
    = image_tag('icons/learning.svg')
    %label Edukacja
  = link_to 'https://github.com/Michanio', class: 'item' do
    = image_tag('icons/GitHub-Mark-120px-plus.png')
    %label GitHub
  =link_to contact_path, class: 'item' do
    = image_tag('icons/mail.svg')
    %label Kontakt

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en"}
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tag

  %body
    .row.fullWidth
      = render 'layouts/navigation'
      = yield